#!/bin/bash

echo -n "please input the client name[client1]:"
read CLIENT
if [ ! $CLIENT ]; then
  CLIENT=client1
fi

echo -n "please input the container name[ovpn]:"
read OVPN
if [ ! $OVPN ]; then
  OVPN=ovpn
fi

docker exec -it $OVPN bash /root/ovpn/gen_client $CLIENT
echo "copy files to clients/ .."
mkdir clients
docker cp $OVPN:/$CLIENT.tar.gz clients/
docker exec -it $OVPN rm /$CLIENT.tar.gz
echo "done"
