#!/bin/bash

echo "开始生成证书及server配置文件.."
if [ ! -d openvpn ] ||
   [ ! -s openvpn/ca.crt ] ||
   [ ! -s openvpn/server.crt ] ||
   [ ! -s openvpn/server.key ] ||
   [ ! -s openvpn/client.crt ] ||
   [ ! -s openvpn/client.key ] ||
   [ ! -s openvpn/dh2048.pem ] ||
   [ ! -s openvpn/ta.key ] ||
   [ ! -s openvpn/server.conf ] ||
   [ ! -s openvpn/client.conf ];
then
  rm -rf openvpn && mkdir openvpn
  docker run -it --rm -v $(pwd)/source:/root/ovpn -v $(pwd)/openvpn:/etc/openvpn ubuntu:14.04 bash /root/ovpn/build
  echo "证书及server配置文件生成完毕.."
else
  echo "证书及server配置文件已经存在.."
fi

echo "开始构建镜像文件.."
docker build -t ovpn .
echo "构建镜像构建完毕.."
